# docker-compose.yml
version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "9911:8000"  # Port mapping to access DynamoDB locally
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    volumes:
      - dynamodb_data:/data

  node-app:
    build:
      context: .  
    container_name: node-app
    ports:
      - "3000:3000"  
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:9911  
    depends_on:
      - dynamodb-local
    volumes:
      - .:/app  

volumes:
  dynamodb_data:
