version: '3'
services:
  api:
    build: ./
    container_name: taes-api
    restart: unless-stopped
    ports:
      - 3002:3000
  dynamodb-local:
    build: .
    ports:
      - "9911:8000"
    volumes:
      - ./docker/dynamodb:/home/dynamodb/data
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=local